### ISSUE TITLE
pharmer get cluster should show the status of cluster object

### ISSUE THREAD

**Issue by sanjid133** [appscode/pharmer#116]
```
NAME      PROVIDER   ZONE            VERSION   RUNNING SINCE
a1        aws        us-west-1a      1.7.4     1d 
```

If cluster is deleted then there is no way to say from the cluster list.

**Comment by aerokite** [comment]
When cluster is deleted successfully, you are supposed to delete Cluster object, I think. Then that will not be appeared in list.

**Comment by aerokite** [comment]
@tamalsaha

**Comment by tamalsaha** [comment]
Users can `purge` the cluster. Then it will be gone from store.
