### ISSUE TITLE
Disable Swap

### ISSUE THREAD

**Issue by tamalsaha** [appscode/pharmer#254]
- `swapoff /dev/partition`
- Disable in /etc/fstab

https://github.com/kubernetes/kubernetes/issues/53533#issuecomment-335219173

	// kubelet log: error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false.
	// https://github.com/kubernetes/kubernetes/issues/50373
	// https://github.com/kubernetes/kubernetes/issues/53533#issuecomment-335219173

**Comment by tamalsaha** [comment]
https://askubuntu.com/questions/440326/how-can-i-turn-off-swap-permanently

https://serverfault.com/a/684792/167143

**Comment by tamalsaha** [comment]
Kubeadm 1.9 will fail if swap enabled: https://github.com/kubernetes/kubernetes/pull/55399

**Comment by vielmetti** [comment]
This is a blocker for Packet, as #257 fails with the following error log:

```
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clust
ers.
[init] Using Kubernetes version: v1.8.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] Some fatal errors occurred:
	running with swap on is not supported. Please disable swap
[preflight] If you know what you are doing, you can skip pre-flight checks with 
`--skip-preflight-checks`
```
