### ISSUE TITLE
Support spot market for Packet

### ISSUE THREAD

**Issue by vielmetti** [appscode/pharmer#263]
Packet supports a "spot market" for instances that are available generally at a discount and that can be terminated when the market price rises. They are ideal for test clusters.

Add support for this spot market in `pharmer`, at least at the step of provisioning.

Docs at Packet: https://help.packet.net/technical/deployment-options/spot-market

Tracking issue for Packet is #257

**Comment by tamalsaha** [comment]
This is supported now.

```console
# create Cluster
pharmer create cluster --provider=packet p4 --zone=ewr1 --credential-uid=packet --kubernetes-version=v1.8.0

# create a node group with node type `spot`
pharmer create ng --nodes=baremetal_2=1 --type=spot --spot-price-max=1 -k p4

# apply
pharmer apply p4
```
